openapi: 3.0.3
info:
  title: Swagger Friends Service - OpenAPI 3.0
  description: ''
  version: '1.0'
paths:
  /create_user/:
    post:
      summary: Create new user
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - id
                - username
              properties:
                id:
                  type: string
                  format: uuid
                  nullable: false
                  description: Unique identifier
                  example: "3fa85f64-5717-4562-b3fc-2c963f66a333"
                username:
                  description: Username
                  type: string
                  nullable: false
      responses:
        '201':
          description: Successfully created
        '400':
          description: Invalid input
  /create_friendship_request/:
    post:
      summary: Create friendship request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - sender
                - receiver
              properties:
                sender:
                  type: string
                  format: uuid
                  nullable: false
                  description: User identifier
                  example: "3fa85f64-5717-4562-b3fc-2c963f66a333"
                receiver:
                  type: string
                  format: uuid
                  nullable: false
                  description: User identifier
                  example: "0eaa7a28-6aa6-4924-b1a9-6ab82c12e299"
      responses:
        '201':
          description: Successfully created
        '400':
          description: Invalid input
        '404':
          description: User not found
  /process_friendship_request/:
    post:
      summary: Accept or reject friendship request
      requestBody:
        content:
          application/json:
            schema:
              type: object
              required:
                - sender
                - receiver
                - action
              properties:
                sender:
                  type: string
                  format: uuid
                  nullable: false
                  description: User identifier
                  example: "3fa85f64-5717-4562-b3fc-2c963f66a333"
                receiver:
                  type: string
                  format: uuid
                  nullable: false
                  description: User identifier
                  example: "0eaa7a28-6aa6-4924-b1a9-6ab82c12e299"
                action:
                  description: action
                  type: string
                  enum:
                    - accept
                    - reject
                  nullable: false
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: User not found
  /get_friendship_requests/:
    get:
      summary: Get all sent and received requests
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
            format: uuid
          description: User identifier
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - sent_requests
                  - received_requests
                properties:
                  sent_requests:
                    type: array
                    items:
                      type: string
                      format: uuid
                      nullable: false
                      description: User identifier
                      example: "3fa85f64-5717-4562-b3fc-2c963f66a333"
                  received_requests:
                    type: array
                    items:
                      type: string
                      format: uuid
                      nullable: false
                      description: User identifier
                      example: "0eaa7a28-6aa6-4924-b1a9-6ab82c12e299"
        '400':
          description: Invalid input
        '404':
          description: User not found
  /get_friendship_status/:
    get:
      summary: Get a status about the relationship between the two users
      parameters:
        - in: query
          name: user_id_1
          schema:
            type: string
            format: uuid
            nullable: false
            example: "3fa85f64-5717-4562-b3fc-2c963f66a333"
          description: First user identifier
        - in: query
          name: user_id_2
          schema:
            type: string
            format: uuid
            nullable: false
            example: "0eaa7a28-6aa6-4924-b1a9-6ab82c12e299"
          description: Second user identifier
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - status
                properties:
                  status:
                    description: status
                    type: string
                    enum:
                      - friends
                      - not_friends
                      - request_sent
                      - request_received
                    nullable: False
        '400':
          description: Invalid input
        '404':
          description: User not found
  /get_user_friends/:
    get:
      summary: Get user's friend identifiers
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
            format: uuid
            nullable: false
            example: "3fa85f64-5717-4562-b3fc-2c963f66a333"
          description: user id
      responses:
        '200':
          description: Successful operation
          content:
            application/json:
              schema:
                type: object
                required:
                  - friends
                properties:
                  friends:
                    type: array
                    items:
                      type: string
                      format: uuid
                      nullable: false
                      description: User identifier
                      example: "0eaa7a28-6aa6-4924-b1a9-6ab82c12e299"

        '400':
          description: Invalid input
        '404':
          description: User not found
  /remove_from_friends/:
    delete:
      summary: Remove spicific user from friends
      parameters:
        - in: query
          name: user_id
          schema:
            type: string
            format: uuid
            nullable: false
            example: "3fa85f64-5717-4562-b3fc-2c963f66a333"
          description: User identifier
        - in: query
          name: friend_id
          schema:
            type: string
            format: uuid
            nullable: false
            example: "0eaa7a28-6aa6-4924-b1a9-6ab82c12e299"
          description: Friend identifier
      responses:
        '200':
          description: Successful operation
        '400':
          description: Invalid input
        '404':
          description: User not found